#!/usr/bin/tclsh
#
# This TCL script scans the opcodes.h file (which is itself generated by
# another TCL script) and the src/vdbe.c source file uses the information
# gleaned to create the opcodeLabels.h source file.
#
# OpcodeLabels.h contains code used by the SQLITE_TREADED_BYTECODE
# optimization.  It creates a static array that contains pointers to
# labels that implement each opcode in the bytecode engine.
#
puts "/* Automatically generated.  Do not edit */"
puts "/* See the tool/mkopcodeLabels.tcl script for details. */"
puts "static const void *aOpcodeLabel\[\] = \173"
set mx 0

set in [open [lindex $argv 0]]
fconfigure $in -translation binary
while {![eof $in]} {
  set line [gets $in]
  if {[regexp {^#define OP_} $line]} {
    set name [lindex $line 1]
    regsub {^OP_} $name {} name
    set i [lindex $line 2]
    set label($i) $name
    if {$mx<$i} {set mx $i}
  }
}
close $in

if {$mx<100} {
  error "mx is too small ($mx).  Something is wrong."
}

set in [open [lindex $argv 1]]
fconfigure $in -translation binary
set previf {}
while {![eof $in]} {
  set line [gets $in]
  if {[regexp {^#if} $line]} {
    set previf $line
    continue
  }
  if {[regexp {^ } $line]} {
    set previf {}
  }
  if {[regexp {^.. Opcode: } $line]} {
    if {$previf ne ""} {
      set opname [lindex $line 2]
      set opif($opname) $previf
    }
  }
}
close $in

for {set i 0} {$i<=$mx} {incr i} {
  set op $label($i)
  if {$op eq "Explain"} {set op Noop}
  set idx [format %3d $i]
  if {[info exists opif($op)]} {
    puts "$opif($op)"
    puts "  /* $idx */ &&opcode_$op,"
    puts "#else"
    puts "  /* $idx */ &&opcode_Noop,"
    puts "#endif"
  } else {
    puts "  /* $idx */ &&opcode_$op,"
  }
}
puts "\175;"
